Section "Device"
  Identifier 	"Intel Integrated Graphics Controller"
  Driver 	"i915"
EndSection

Section "Monitor"
  Identifier 	"AOC 511Vwb"
  VendorName 	"AOC"
  ModelName 	"511Vwb"
  Modeline 	"1280x768_60.00" 80.14 1280 1344 1480 1680 768 769 772 795 -HSync +Vsync
  Modeline 	"1024x768_60.00" 64.11 1024 1080 1184 1344 768 769 772 795 -HSync +Vsync
  Modeline 	"800x600_60.00" 38.22 800 832 912 1024 600 601 604 622 -HSync +Vsync
  HorizSync 	30-63
  VertRefresh 	55-80
  Option	"PreferredMode" "1280x768_60.00"
EndSection  

Section "Screen"
  Identifier 	"Screen0"
  Device 	"Intel Integrated Graphics Controller"
  Monitor 	"AOC 511Vwb"
EndSection

Section "ServerLayout"
  Identifier 	"Layout"
  Screen 	"Screen0"
EndSection