" General: ----------------------------------------------------------------- {{{

set fdm=marker
set nocp
set nocompatible                    " Use Vim settings, rather then Vi settings.
set clipboard=unnamed
set autoindent                      " copy indent from current line
set autoread                        " read open files again when changed outside Vim
set autowrite                       " write a modified buffer on each :next , ...
set backspace=indent,eol,start      " backspacing over everything in insert mode
set backup                          " keep a backup file
set incsearch                       " do incremental searching
set nowrap                          " do not wrap lines
set ruler                           " show the cursor position all the time
set showcmd                         " display incomplete commands
set autoindent                      " smart autoindenting when starting a new line
set expandtab
set shiftwidth=4
set softtabstop=4                   " number of spaces that a <Tab> counts for
set wildmenu                        " command-line completion in an enhanced mode
set number                          " show line numbers.
set relativenumber
set background=dark
set diffopt=vertical                " always display diffs in a vertical pane

set guioptions-=m                   " remove menu bar
set guioptions-=T                   " remove toolbar
set guioptions-=r                   " remove right-hand scroll bar
set guioptions-=L                   " remove left-hand scroll bar

syntax on

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
set guifont=D2Coding\ for\ Powerline:h13

if !isdirectory($HOME . "/.vim/backup")
    if has("win64") || has("win32") || has("win16")
        silent !mkdir $HOME/.vim/backup
    else
        silent !mkdir -p $HOME/.vim/backup
    endif
endif

if !isdirectory($HOME . "/.vim/swap")
    if has("win64") || has("win32") || has("win16")
        silent !mkdir $HOME/.vim/swap
    else
        silent !mkdir -p $HOME/.vim/swap
    endif
endif

if !isdirectory($HOME . "/.vim/backup")
    if has("win64") || has("win32") || has("win16")
        silent !mkdir $HOME/.vim/undo
    else
        silent !mkdir -p $HOME/.vim/undo
    endif
endif

" The current directory is the directory of the file in the current window.
if has("autocmd")
  autocmd BufEnter * :lchdir %:p:h
endif

" Always jump to the last known cursor position.
if has("autocmd")
  autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
endif


" ------------------------------------------------------------------------- }}}"

" Mappings: ---------------------------------------------------------------- {{{

" F2 for saving current buffer.
inoremap <silent> <F2> <ESC> :write <CR> 
nnoremap <silent> <F2> :write <CR>

" F3 for closing/opening NERDTree's panel.
map <F3> :NERDTreeToggle<cr>

" F4 for closing/opening Tagbar's panel.
map <F4> :TagbarToggle<cr>
" -------------------------------------------------------------------------- }}}

" Plugins Settings --------------------------------------------------------- {{{

let NERDTreeAutoCenter          = 1 "auto center is on
let NERDTreeCaseSensitiveSort   = 1 "case sensitive sorting is on
let NERDTreeChDirMode           = 2 "set the CWD to the current root
let NERDTreeSortOrder           = ['\.h$', '\.c$', '\.cpp$', '*', '\/$' ]

" Supertab
let g:SuperTabMappingForward    = '<s-tab>'
let g:SuperTabMappingBackward   = '<tab>'

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list    = 1
let g:syntastic_auto_loc_list               = 1
let g:syntastic_check_on_open               = 0
let g:syntastic_check_on_wq                 = 0

" Rust
let g:rustfmt_autosave                      = 1
let g:rustfm_options                        = '--write-mode=overwrite'

" Clojure
let g:clojure_align_multiline_strings       = 0

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" Powerline
set laststatus=2
let g:airline_powerline_fonts               = 1
" -------------------------------------------------------------------------- }}}

" Vundle: ------------------------------------------------------------------ {{{

let is_vundle_installed = 0

if !isdirectory($HOME . "/.vim/bundle/Vundle.vim")
    silent !mkdir -p $HOME/.vim/bundle
    silent !git clone https://github.com/gmarik/Vundle.vim $HOME/.vim/bundle/Vundle.vim
    let is_vundle_installed = 1
endif

set rtp+=~/.vim/bundle/Vundle.vim
filetype off

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'       " Plugin manager.
Plugin 'scrooloose/nerdtree'        " File tree navigation.
Plugin 'Raimondi/delimitMate'       " Automatically insert quotes, parentheses, braces etc.
Plugin 'tpope/vim-surround'         " Surrounds text blocks with tags, brackets etc.
Plugin 'Yggdroot/indentLine'        " Displays identation levels with thin vertical lines.
Plugin 'tomasr/molokai'             " Molokai colors cheme.
Plugin 'davidhalter/jedi-vim'       " Python auto completion.
Plugin 'ervandew/supertab'          " Insert completion with <TAB>.
Plugin 'elzr/vim-json'              " Improved syntax highlighting fro JSON files.
Plugin 'rust-lang/rust.vim'         " Rust file detection, syntax highlighting etc.
Plugin 'scrooloose/syntastic'       " Syntax checker.
Plugin 'bitc/vim-bad-whitespace'    " Highlights white space and the end of lines.
Plugin 'tpope/vim-salve'            " Static Vim support for Leiningen and Boot.
Plugin 'tpope/vim-fireplace'        " Clojure REPL.
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'vim-airline/vim-airline'

call vundle#end()

filetype plugin indent on

if is_vundle_installed == 1
    :silent! PluginInstall
    :qa
endif

colorscheme molokai
" --------------------------------------------------------------------------- }}}

