(setenv "LSP_USE_PLISTS" "true")

(setq gc-cons-threshold 10000000)
(setq read-process-output-max (* 1024 1024))
(setq byte-compile-warnings '(not obsolete))
(setq warning-suppress-log-types '((comp) (bytecomp)))
(setq native-comp-async-report-warnings-errors 'silent)
(setq inhibit-startup-echo-area-message (user-login-name))
(setq frame-resize-pixelwise t)
(setq default-frame-alist '((fullscreen . maximized)
                            (ns-transparent-titlebar . t)))

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
