# brew install
brew "asdf"
brew "stow"
brew "fzf"
brew "gh"
brew "docker-compose"
brew "docker-buildx"
brew "libpq"

# brew install --cask
cask "alt-tab"
cask "logseq"
cask "google-cloud-sdk"
cask "ghostty"
