# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="lambda"

plugins=(git git git-extras)

PATH=$PATH:~/bin
PATH=$PATH:~/.cargo/bin

export PROJECTS_DIR=$HOME/code/projects

source $ZSH/oh-my-zsh.sh
source $PROJECTS_DIR/dotfiles/zsh/java.sh
source $PROJECTS_DIR/dotfiles/zsh/python.sh
source $PROJECTS_DIR/dotfiles/zsh/system.sh
source $PROJECTS_DIR/dotfiles/zsh/android.sh
source $PROJECTS_DIR/dotfiles/zsh/nodejs.sh

source $PROJECTS_DIR/dotfiles/zsh/secret.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
