# Path to your oh-my-zsh configuration.
ZSH_DISABLE_COMPFIX=true
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="lambda"

plugins=(git git git-extras vi-mode zsh-z)

PATH=$PATH:~/bin
PATH=$PATH:~/.cargo/bin

export PROJECTS_DIR=$HOME/code/projects/personal
export TOOLS_DIR=$HOME/code/tools

autoload -U colors; colors

source $ZSH/oh-my-zsh.sh
source $PROJECTS_DIR/dotfiles/zsh/python.sh
source $PROJECTS_DIR/dotfiles/zsh/system.sh
source $PROJECTS_DIR/dotfiles/zsh/android.sh
source $PROJECTS_DIR/dotfiles/zsh/nodejs.sh
source $PROJECTS_DIR/dotfiles/zsh/aws.sh
source $PROJECTS_DIR/dotfiles/zsh/postgres.sh
source $PROJECTS_DIR/dotfiles/zsh/ruby.sh
source $PROJECTS_DIR/dotfiles/zsh/rust.sh
source $PROJECTS_DIR/dotfiles/zsh/k8s.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Must be at the end of the file.
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
