export ZSH_DISABLE_COMPFIX=true
export ZSH_THEME="lambda"

export plugins=(git git git-extras vi-mode z)

ZSH=$HOME/.oh-my-zsh
PATH=$PATH:~/bin
PATH=$PATH:~/.cargo/bin

export PROJECTS_DIR=$HOME/Projects/Personal
export NVM_DIR="$HOME/.nvm"

autoload -U colors; colors

source "$ZSH"/oh-my-zsh.sh
source "$PROJECTS_DIR"/dotfiles/zsh/python.sh
source "$PROJECTS_DIR"/dotfiles/zsh/system.sh

# shellcheck disable=SC1090
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Must be at the end of the file.
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
